insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (1, 266, 'Karstens', 'Ostankinskiy', 3120, true, 1);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (2, 55, '6th', 'Visby', 6948, false, 2);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (3, 108, 'Pierstorff', 'Los Frentones', 4294, false, 3);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (4, 337, 'Kenwood', 'Solec Nad Wisłą', 7305, true, 4);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (5, 127, 'Judy', 'Beolgyo', 7463, true, 5);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (6, 31, 'Eastwood', 'Berlin', 6868, true, 6);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (7, 206, 'Larry', 'Del Valle', 5533, false, 7);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (8, 296, 'Buhler', 'Mancos', 5881, false, 8);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (9, 341, 'Debs', 'Pancoran', 1229, true, 9);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (10, 113, 'Village', 'Kitakyūshū', 3647, true, 10);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (11, 146, 'Ridge Oak', 'Praia da Barra', 1305, false, 11);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (12, 65, 'Valley Edge', 'Waihi', 1840, false, 12);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (13, 220, 'Russell', 'Changqiao', 1553, false, 13);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (14, 320, 'Havey', 'Shajing', 6791, true, 14);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (15, 297, 'Comanche', 'Brooklyn', 7667, false, 15);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (16, 120, 'Dorton', 'Tanxi', 3514, false, 16);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (17, 340, 'Manufacturers', 'Aurora', 4156, false, 17);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (18, 9, 'Kensington', 'Guaranésia', 3683, false, 18);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (19, 28, 'Fairview', 'Gorna Oryakhovitsa', 6852, true, 19);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (20, 165, 'Bobwhite', 'Jugezhuang', 6451, true, 20);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (21, 123, 'Sycamore', 'Dire Dawa', 4475, true, 21);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (22, 336, 'Debra', 'Fresno', 6382, true, 22);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (23, 197, 'Duke', 'Mahendranagar', 6686, true, 23);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (24, 260, 'Transport', 'Inari', 5629, false, 24);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (25, 185, 'Division', 'Cigintung', 2741, true, 25);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (26, 115, 'Jay', 'Hongqi', 2685, true, 26);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (27, 262, 'Evergreen', 'Krasnorechenskiy', 6268, false, 27);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (28, 157, 'Gina', 'Inicbulan', 5822, true, 28);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (29, 120, 'Bobwhite', 'Mianhu', 6914, true, 29);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (30, 293, 'Carioca', 'Vesoul', 4018, false, 30);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (31, 214, 'Hauk', 'Haveluloto', 6348, false, 31);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (32, 138, 'Clove', 'Gorzów Wielkopolski', 4523, true, 32);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (33, 245, 'Nova', 'Wenqiao', 7850, false, 33);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (34, 173, 'Glacier Hill', 'Ilare', 6010, false, 34);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (35, 260, 'Ridgeway', 'Taranovskoye', 6363, false, 35);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (36, 3, 'Clarendon', 'Casalinho', 3377, true, 36);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (37, 302, 'Lukken', 'Ubud', 4871, true, 37);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (38, 202, 'Fremont', 'Nong Phai', 2990, true, 38);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (39, 346, 'Sauthoff', 'Bayonne', 7448, true, 39);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (40, 167, 'Lunder', 'Dunhao', 3577, true, 40);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (41, 25, 'Tennessee', 'Ōtsuchi', 3375, false, 41);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (42, 161, 'Toban', 'Suya', 6112, true, 42);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (43, 306, 'Lotheville', 'Kranggan', 2323, false, 43);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (44, 123, 'Clove', 'Kambar', 4831, false, 44);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (45, 4, 'Prairieview', 'Sandakan', 7769, true, 45);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (46, 128, 'Moulton', 'Milwaukee', 3726, false, 46);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (47, 22, 'Elgar', 'Singkup', 3763, false, 47);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (48, 58, 'Corben', 'Neglasari', 4283, true, 48);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (49, 113, 'Morningstar', 'Marseille', 6079, true, 49);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (50, 189, 'Basil', 'Tanzhou', 3814, true, 50);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (51, 317, 'Saint Paul', 'Madīnat Ḩamad', 1796, false, 51);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (52, 229, 'Crownhardt', 'Camaçari', 6760, true, 52);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (53, 169, 'Sauthoff', 'Kamenický Šenov', 2915, true, 53);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (54, 273, 'Sherman', 'Pishaj', 4242, false, 54);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (55, 123, 'East', 'Horad Smalyavichy', 7689, true, 55);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (56, 8, 'Arrowood', 'London', 5214, false, 56);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (57, 312, 'Lighthouse Bay', 'Pailou', 3847, false, 57);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (58, 241, 'Kinsman', 'Junik', 6956, false, 58);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (59, 132, 'Crowley', 'Las Vegas', 1883, true, 59);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (60, 24, 'Tennessee', 'Vicente Guerrero', 6484, true, 60);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (61, 106, 'Hintze', 'Stare Kurowo', 7871, true, 61);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (62, 68, 'Green Ridge', 'Madison', 1880, false, 62);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (63, 54, 'Maple', 'Arraial do Cabo', 5120, true, 63);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (64, 226, 'Victoria', 'Qixingtai', 4716, true, 64);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (65, 88, 'Elka', 'Qinglung', 1498, false, 65);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (66, 268, 'Washington', 'Loma Bonita', 4774, true, 66);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (67, 272, 'Armistice', 'Gulao', 1680, false, 67);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (68, 350, 'Sheridan', 'Massy', 2607, false, 68);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (69, 93, 'Barnett', 'Międzybrodzie Bialskie', 5955, true, 69);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (70, 54, 'Summerview', 'Cagdianao', 1775, true, 70);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (71, 209, 'Novick', 'Padangan', 6564, true, 71);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (72, 95, 'Quincy', 'Slatina', 2469, true, 72);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (73, 68, 'Daystar', 'Trakai', 3187, false, 73);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (74, 258, 'Ryan', 'El Porvenir', 2653, true, 74);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (75, 21, 'Londonderry', 'Jiashi', 4618, false, 75);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (76, 292, 'Blaine', 'Tabu', 5808, true, 76);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (77, 277, 'Harper', 'Huangzhuang', 4980, false, 77);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (78, 322, 'David', 'Darungan', 3785, true, 78);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (79, 215, 'Dovetail', 'Huangtan', 4080, true, 79);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (80, 304, 'Crescent Oaks', 'Ardazubre', 7819, false, 80);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (81, 246, 'Rieder', 'Weichanglu', 4896, false, 81);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (82, 104, 'David', 'Melrose', 4419, false, 82);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (83, 20, 'Old Gate', 'Lincheng', 1377, true, 83);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (84, 256, 'Gerald', 'Kitakyūshū', 5359, true, 84);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (85, 260, 'Red Cloud', 'Barroco', 1814, false, 85);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (86, 264, 'Monument', 'Rungis', 2346, false, 86);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (87, 213, 'Harper', 'Pamiers', 4689, false, 87);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (88, 75, 'Ryan', 'Tyszowce', 6215, true, 88);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (89, 20, 'Morningstar', 'Miki', 4171, false, 89);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (90, 175, 'Declaration', 'Sumurgeneng', 4660, true, 90);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (91, 279, 'Sheridan', 'Salavat', 3483, true, 91);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (92, 291, 'Swallow', 'Debar', 3584, true, 92);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (93, 126, 'Crowley', 'Leipzig', 1832, true, 93);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (94, 175, 'Muir', 'Kakan', 6369, false, 94);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (95, 23, 'Oakridge', 'Barusuda', 3629, false, 95);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (96, 218, 'Green Ridge', 'Urpay', 2999, false, 96);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (97, 348, 'Mandrake', 'Maopingchang', 5027, true, 97);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (98, 266, 'Redwing', 'Changtang', 2450, true, 98);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (99, 257, 'Clemons', 'Horokhiv', 5208, false, 99);
insert into livraisons (id, numeroRueL, rueL, villeL, codePostalL, estLivre, commandeId) values (100, 291, 'Reinke', 'Darenzhuang', 5169, true, 100);