-- MySQL Script generated by MySQL Workbench
-- Thu Nov 17 17:37:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DbFormation
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DbFormation` ;

-- -----------------------------------------------------
-- Schema DbFormation
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DbFormation` DEFAULT CHARACTER SET utf8 ;
USE `DbFormation` ;

-- -----------------------------------------------------
-- Table `DbFormation`.`Roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DbFormation`.`Roles` ;

CREATE TABLE IF NOT EXISTS `DbFormation`.`Roles` (
  `idRoles` INT NOT NULL AUTO_INCREMENT,
  `denomination` VARCHAR(70) NOT NULL,
  `actif` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idRoles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DbFormation`.`Utilisateurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DbFormation`.`Utilisateurs` ;

CREATE TABLE IF NOT EXISTS `DbFormation`.`Utilisateurs` (
  `idUtilisateurs` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  `prenom` VARCHAR(100) NOT NULL,
  `mail` VARCHAR(100) NOT NULL,
  `NRN` INT NOT NULL,
  `sexe` ENUM('M', 'F', 'X') NOT NULL,
  `actif` TINYINT NOT NULL DEFAULT 1,
  `rolesidRoles` INT NOT NULL,
  PRIMARY KEY (`idUtilisateurs`),
  INDEX `fk_Utilisateurs_Roles_idx` (`rolesidRoles` ASC) VISIBLE,
  CONSTRAINT `fk_Utilisateurs_Roles`
    FOREIGN KEY (`rolesidRoles`)
    REFERENCES `DbFormation`.`Roles` (`idRoles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DbFormation`.`Permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DbFormation`.`Permissions` ;

CREATE TABLE IF NOT EXISTS `DbFormation`.`Permissions` (
  `idPermissions` INT NOT NULL AUTO_INCREMENT,
  `action` VARCHAR(150) NOT NULL,
  `type` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idPermissions`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DbFormation`.`Categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DbFormation`.`Categories` ;

CREATE TABLE IF NOT EXISTS `DbFormation`.`Categories` (
  `idCategories` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  `actif` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idCategories`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DbFormation`.`Formations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DbFormation`.`Formations` ;

CREATE TABLE IF NOT EXISTS `DbFormation`.`Formations` (
  `idFormations` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(150) NOT NULL,
  `infos` TEXT NULL,
  `actif` TINYINT NULL DEFAULT 1,
  `dateLimiteInscription` DATE NOT NULL,
  `dateQuestionnaire` DATE NOT NULL,
  `categoriesIdCategories` INT NOT NULL,
  `utilisateursIdUtilisateurs` INT NOT NULL,
  PRIMARY KEY (`idFormations`),
  INDEX `fk_Formations_Categories1_idx` (`categoriesIdCategories` ASC) VISIBLE,
  INDEX `fk_Formations_Utilisateurs1_idx` (`utilisateursIdUtilisateurs` ASC) VISIBLE,
  CONSTRAINT `fk_Formations_Categories1`
    FOREIGN KEY (`categoriesIdCategories`)
    REFERENCES `DbFormation`.`Categories` (`idCategories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Formations_Utilisateurs1`
    FOREIGN KEY (`utilisateursIdUtilisateurs`)
    REFERENCES `DbFormation`.`Utilisateurs` (`idUtilisateurs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DbFormation`.`Diplomes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DbFormation`.`Diplomes` ;

CREATE TABLE IF NOT EXISTS `DbFormation`.`Diplomes` (
  `idDiplomes` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(150) NOT NULL,
  `formationsIdFormations` INT NOT NULL,
  PRIMARY KEY (`idDiplomes`),
  INDEX `fk_Diplomes_Formations1_idx` (`formationsIdFormations` ASC) VISIBLE,
  CONSTRAINT `fk_Diplomes_Formations1`
    FOREIGN KEY (`formationsIdFormations`)
    REFERENCES `DbFormation`.`Formations` (`idFormations`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DbFormation`.`Syllabus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DbFormation`.`Syllabus` ;

CREATE TABLE IF NOT EXISTS `DbFormation`.`Syllabus` (
  `idSyllabus` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(150) NOT NULL,
  `chemin` VARCHAR(255) NOT NULL,
  `actif` TINYINT NOT NULL DEFAULT 1,
  `formationsIdFormations` INT NOT NULL,
  PRIMARY KEY (`idSyllabus`),
  INDEX `fk_Syllabus_Formations1_idx` (`formationsIdFormations` ASC) VISIBLE,
  CONSTRAINT `fk_Syllabus_Formations1`
    FOREIGN KEY (`formationsIdFormations`)
    REFERENCES `DbFormation`.`Formations` (`idFormations`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DbFormation`.`Roles_Permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DbFormation`.`Roles_Permissions` ;

CREATE TABLE IF NOT EXISTS `DbFormation`.`Roles_Permissions` (
  `idRolesPermissions` INT NOT NULL AUTO_INCREMENT,
  `rolesIdRoles` INT NOT NULL,
  `permissionsIdPermissions` INT NOT NULL,
  INDEX `fk_Roles_has_Permissions_Permissions1_idx` (`permissionsIdPermissions` ASC) VISIBLE,
  INDEX `fk_Roles_has_Permissions_Roles1_idx` (`rolesIdRoles` ASC) VISIBLE,
  PRIMARY KEY (`idRolesPermissions`),
  CONSTRAINT `fk_Roles_has_Permissions_Roles1`
    FOREIGN KEY (`rolesIdRoles`)
    REFERENCES `DbFormation`.`Roles` (`idRoles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Roles_has_Permissions_Permissions1`
    FOREIGN KEY (`permissionsIdPermissions`)
    REFERENCES `DbFormation`.`Permissions` (`idPermissions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DbFormation`.`Utilisateurs_Categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DbFormation`.`Utilisateurs_Categories` ;

CREATE TABLE IF NOT EXISTS `DbFormation`.`Utilisateurs_Categories` (
  `idUtilisateursCategories` INT NOT NULL AUTO_INCREMENT,
  `utilisateursIdUtilisateurs` INT NOT NULL,
  `categoriesIdCategories` INT NOT NULL,
  INDEX `fk_Utilisateurs_has_Categorie_Categorie1_idx` (`categoriesIdCategories` ASC) VISIBLE,
  INDEX `fk_Utilisateurs_has_Categorie_Utilisateurs1_idx` (`utilisateursIdUtilisateurs` ASC) VISIBLE,
  PRIMARY KEY (`idUtilisateursCategories`),
  CONSTRAINT `fk_Utilisateurs_has_Categorie_Utilisateurs1`
    FOREIGN KEY (`utilisateursIdUtilisateurs`)
    REFERENCES `DbFormation`.`Utilisateurs` (`idUtilisateurs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utilisateurs_has_Categorie_Categorie1`
    FOREIGN KEY (`categoriesIdCategories`)
    REFERENCES `DbFormation`.`Categories` (`idCategories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DbFormation`.`Questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DbFormation`.`Questions` ;

CREATE TABLE IF NOT EXISTS `DbFormation`.`Questions` (
  `idQuestions` INT NOT NULL,
  `question` VARCHAR(250) NOT NULL,
  `cote` FLOAT NOT NULL,
  `actif` TINYINT NOT NULL,
  `formationsIdFormations` INT NOT NULL,
  PRIMARY KEY (`idQuestions`),
  INDEX `fk_Questions_Formations1_idx` (`formationsIdFormations` ASC) VISIBLE,
  CONSTRAINT `fk_Questions_Formations1`
    FOREIGN KEY (`formationsIdFormations`)
    REFERENCES `DbFormation`.`Formations` (`idFormations`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DbFormation`.`Reponses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DbFormation`.`Reponses` ;

CREATE TABLE IF NOT EXISTS `DbFormation`.`Reponses` (
  `idReponses` INT NOT NULL AUTO_INCREMENT,
  `reponse` VARCHAR(45) NULL,
  `coteAttribue` FLOAT NULL,
  `questionsIdQuestions` INT NOT NULL,
  `utilisateursIdUtilisateurs` INT NOT NULL,
  PRIMARY KEY (`idReponses`),
  INDEX `fk_Reponses_Questions1_idx` (`questionsIdQuestions` ASC) VISIBLE,
  INDEX `fk_Reponses_Utilisateurs1_idx` (`utilisateursIdUtilisateurs` ASC) VISIBLE,
  CONSTRAINT `fk_Reponses_Questions1`
    FOREIGN KEY (`questionsIdQuestions`)
    REFERENCES `DbFormation`.`Questions` (`idQuestions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reponses_Utilisateurs1`
    FOREIGN KEY (`utilisateursIdUtilisateurs`)
    REFERENCES `DbFormation`.`Utilisateurs` (`idUtilisateurs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DbFormation`.`Diplomes_Utilisateurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DbFormation`.`Diplomes_Utilisateurs` ;

CREATE TABLE IF NOT EXISTS `DbFormation`.`Diplomes_Utilisateurs` (
  `idDiplomesUtilisateurs` INT NOT NULL AUTO_INCREMENT,
  `diplomesIdDiplomes` INT NOT NULL,
  `utilisateursIdUtilisateurs` INT NOT NULL,
  INDEX `fk_Diplomes_has_Utilisateurs_Utilisateurs1_idx` (`utilisateursIdUtilisateurs` ASC) VISIBLE,
  INDEX `fk_Diplomes_has_Utilisateurs_Diplomes1_idx` (`diplomesIdDiplomes` ASC) VISIBLE,
  PRIMARY KEY (`idDiplomesUtilisateurs`),
  CONSTRAINT `fk_Diplomes_has_Utilisateurs_Diplomes1`
    FOREIGN KEY (`diplomesIdDiplomes`)
    REFERENCES `DbFormation`.`Diplomes` (`idDiplomes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Diplomes_has_Utilisateurs_Utilisateurs1`
    FOREIGN KEY (`utilisateursIdUtilisateurs`)
    REFERENCES `DbFormation`.`Utilisateurs` (`idUtilisateurs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
